"""account

Revision ID: 476cea0d4f6b
Revises: 2bbdefea5885
Create Date: 2021-02-18 10:53:49.756435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '476cea0d4f6b'
down_revision = '2bbdefea5885'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('access_key', sa.String(), nullable=True),
    sa.Column('secret_key', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_table('accounts')
    # ### end Alembic commands ###
